spring:
  profiles:
    active: native
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations     # Looks for config files in resources/configurations

server:
  port: 8888
